import { 
  Workspace, 
  WorkspaceMember, 
  Project, 
  Task, 
  Skill, 
  Invoice, 
  Document, 
  AIRecommendation,
  Client,
  Expense,
  ActivityLog,
  TaskHistory
} from '@/types';

/**
 * MOCK SETUP CONFIGURATION
 * Set ENABLE_MOCK_PROFILE to false to disable mock profile & revert to pure Supabase auth.
 */
export const ENABLE_MOCK_PROFILE = false;

export const MOCK_CREDENTIALS = {
  email: 'founder@example.com',
  company: 'Demo Agency',
  founderName: 'Demo Founder',
  founderRole: 'Founder & CEO',
};

export const LEADLINKED_WORKSPACE: Workspace = {
  id: 'ws_leadlinked_01',
  name: 'LeadLinked',
  slug: 'leadlinked',
  owner_id: 'usr_shezan_founder',
  currency: 'USD',
  timezone: 'UTC+05:30 (IST)',
  created_at: '2026-08-01T08:00:00Z',
};

export const LEADLINKED_MEMBERS: WorkspaceMember[] = [
  {
    id: 'mem_shezan',
    workspace_id: 'ws_leadlinked_01',
    user_id: 'usr_shezan_founder',
    name: 'Mohammed Shezan Ahmed',
    email: 'techtone546@gmail.com',
    role: 'owner',
    designation: 'Founder & CEO',
    workload_percentage: 60,
    status: 'active',
    joined_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'mem_ajay',
    workspace_id: 'ws_leadlinked_01',
    user_id: 'usr_ajay_02',
    name: 'Ajay Verma',
    email: 'ajay@leadlinked.io',
    role: 'member',
    designation: 'Senior Frontend & Copy Lead',
    workload_percentage: 45,
    status: 'active',
    joined_at: '2026-08-03T09:00:00Z',
  },
  {
    id: 'mem_sara',
    workspace_id: 'ws_leadlinked_01',
    user_id: 'usr_sara_03',
    name: 'Sara Lin',
    email: 'sara@leadlinked.io',
    role: 'admin',
    designation: 'Fullstack & Cloud Architect',
    workload_percentage: 85,
    status: 'busy',
    joined_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'mem_ahmed',
    workspace_id: 'ws_leadlinked_01',
    user_id: 'usr_ahmed_04',
    name: 'Ahmed Tariq',
    email: 'ahmed@leadlinked.io',
    role: 'member',
    designation: 'UI/UX & Design Systems',
    workload_percentage: 95,
    status: 'busy',
    joined_at: '2026-08-04T11:00:00Z',
  },
  {
    id: 'mem_elena',
    workspace_id: 'ws_leadlinked_01',
    user_id: 'usr_elena_05',
    name: 'Elena Rostova',
    email: 'elena@leadlinked.io',
    role: 'member',
    designation: 'Growth & Client Ops',
    workload_percentage: 35,
    status: 'active',
    joined_at: '2026-08-05T08:30:00Z',
  },
];

export const LEADLINKED_CLIENTS: Client[] = [
  {
    id: 'cli_01',
    workspace_id: 'ws_leadlinked_01',
    name: 'Marcus Vance',
    company_name: 'Apex Dynamics Corp',
    email: 'marcus@apexdynamics.com',
    status: 'active',
    total_billed: 42500,
    created_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'cli_02',
    workspace_id: 'ws_leadlinked_01',
    name: 'Rachel Sterling',
    company_name: 'FinFlow Global',
    email: 'rachel@finflow.io',
    status: 'active',
    total_billed: 68000,
    created_at: '2026-08-04T11:30:00Z',
  },
  {
    id: 'cli_03',
    workspace_id: 'ws_leadlinked_01',
    name: 'Liam Zhang',
    company_name: 'Kroma Studio',
    email: 'liam@kromastudio.design',
    status: 'active',
    total_billed: 24000,
    created_at: '2026-08-06T14:00:00Z',
  },
];

export const LEADLINKED_SKILLS: Skill[] = [
  { id: 'sk_1', user_id: 'usr_ajay_02', workspace_id: 'ws_leadlinked_01', skill_name: 'B2B Copywriting & Cold Email Hooks', score: 9.5, category: 'content', verified_tasks_count: 38 },
  { id: 'sk_2', user_id: 'usr_ajay_02', workspace_id: 'ws_leadlinked_01', skill_name: 'React / Next.js Development', score: 8.9, category: 'engineering', verified_tasks_count: 26 },
  { id: 'sk_3', user_id: 'usr_ajay_02', workspace_id: 'ws_leadlinked_01', skill_name: 'Client Proposal Architecture', score: 9.2, category: 'content', verified_tasks_count: 21 },
  
  { id: 'sk_4', user_id: 'usr_sara_03', workspace_id: 'ws_leadlinked_01', skill_name: 'PostgreSQL & Supabase Multi-Tenancy', score: 9.7, category: 'engineering', verified_tasks_count: 51 },
  { id: 'sk_5', user_id: 'usr_sara_03', workspace_id: 'ws_leadlinked_01', skill_name: 'FastAPI & Microservices Architecture', score: 9.3, category: 'engineering', verified_tasks_count: 32 },
  { id: 'sk_6', user_id: 'usr_sara_03', workspace_id: 'ws_leadlinked_01', skill_name: 'DevOps & Docker Deployment', score: 8.8, category: 'engineering', verified_tasks_count: 19 },
  
  { id: 'sk_7', user_id: 'usr_ahmed_04', workspace_id: 'ws_leadlinked_01', skill_name: 'Figma & Apple Keynote Design Systems', score: 9.8, category: 'design', verified_tasks_count: 55 },
  { id: 'sk_8', user_id: 'usr_ahmed_04', workspace_id: 'ws_leadlinked_01', skill_name: 'Interactive Data Visualizations & Flowcharts', score: 9.1, category: 'design', verified_tasks_count: 34 },
  { id: 'sk_9', user_id: 'usr_ahmed_04', workspace_id: 'ws_leadlinked_01', skill_name: 'Landing Page Conversion UX', score: 9.4, category: 'marketing', verified_tasks_count: 29 },

  { id: 'sk_10', user_id: 'usr_elena_05', workspace_id: 'ws_leadlinked_01', skill_name: 'Client SLA & Legal Agreements', score: 9.6, category: 'operations', verified_tasks_count: 44 },
  { id: 'sk_11', user_id: 'usr_elena_05', workspace_id: 'ws_leadlinked_01', skill_name: 'Stripe Billing & Cashflow Management', score: 9.0, category: 'operations', verified_tasks_count: 33 },
];

export const LEADLINKED_PROJECTS: Project[] = [
  {
    id: 'prj_01',
    workspace_id: 'ws_leadlinked_01',
    name: 'LeadLinked B2B Outbound Engine',
    client_name: 'LeadLinked Core',
    description: 'Autonomous multi-channel lead enrichment, cold outreach sequencing, and CRM bi-directional sync.',
    budget: 35000,
    deadline: '2026-08-30',
    status: 'active',
    health_score: 95,
    lead_member_id: 'mem_shezan',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prj_02',
    workspace_id: 'ws_leadlinked_01',
    name: 'Apex Robotics SaaS Redesign',
    client_name: 'Apex Dynamics Corp',
    description: 'Complete brand repositioning, dark dashboard UI system, and customer telemetry portal.',
    budget: 28500,
    deadline: '2026-08-28',
    status: 'active',
    health_score: 92,
    lead_member_id: 'mem_ahmed',
    created_at: '2026-08-03T12:00:00Z',
  },
  {
    id: 'prj_03',
    workspace_id: 'ws_leadlinked_01',
    name: 'FinFlow High-Frequency Engine',
    client_name: 'FinFlow Global',
    description: 'PostgreSQL multi-tenant database migration and real-time ledger pipeline.',
    budget: 45000,
    deadline: '2026-08-25',
    status: 'warning',
    health_score: 68,
    lead_member_id: 'mem_sara',
    created_at: '2026-08-05T14:00:00Z',
  },
  {
    id: 'prj_04',
    workspace_id: 'ws_leadlinked_01',
    name: 'Kroma Brand Identity & Asset System',
    client_name: 'Kroma Studio',
    description: 'Design tokens, sales page copy, and vector asset generation suite.',
    budget: 16000,
    deadline: '2026-08-22',
    status: 'critical',
    health_score: 42,
    lead_member_id: 'mem_ahmed',
    created_at: '2026-08-08T09:00:00Z',
  },
];

export const LEADLINKED_TASKS: Task[] = [
  {
    id: 'tsk_01',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_01',
    project_name: 'LeadLinked B2B Outbound Engine',
    title: 'Deploy Apollo & LinkedIn automated enricher webhooks',
    description: 'Set up real-time prospect validation and email deliverability verify pipeline.',
    assigned_to: 'mem_sara',
    priority: 'urgent',
    status: 'doing',
    required_skills: ['FastAPI & Microservices Architecture', 'PostgreSQL & Supabase Multi-Tenancy'],
    estimated_hours: 8,
    deadline: '2026-08-22',
    created_at: '2026-08-15T09:00:00Z',
  },
  {
    id: 'tsk_02',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_04',
    project_name: 'Kroma Brand Identity & Asset System',
    title: 'High-converting sales proposal copywriting & value proposition',
    description: 'Write 5 core benefit pillars, founder story, and clear call-to-action structure.',
    assigned_to: 'mem_ahmed', // Intentionally mismatched to trigger AI recommendation to Ajay
    priority: 'urgent',
    status: 'blocked',
    required_skills: ['B2B Copywriting & Cold Email Hooks', 'Landing Page Conversion UX'],
    estimated_hours: 6,
    deadline: '2026-08-21',
    created_at: '2026-08-16T10:00:00Z',
  },
  {
    id: 'tsk_03',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_02',
    project_name: 'Apex Robotics SaaS Redesign',
    title: 'Audit and finalise dark minimalist component tokens',
    description: 'Extract border radiuses, surface opacities, and typography hierarchy for customer dashboard.',
    assigned_to: 'mem_ahmed',
    priority: 'high',
    status: 'completed',
    required_skills: ['Figma & Apple Keynote Design Systems'],
    estimated_hours: 6,
    deadline: '2026-08-18',
    created_at: '2026-08-12T10:00:00Z',
    completed_at: '2026-08-18T17:00:00Z',
  },
  {
    id: 'tsk_04',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_01',
    project_name: 'LeadLinked B2B Outbound Engine',
    title: 'Design interactive AI Operations Manager cockpit widgets',
    description: 'Create responsive recommendation review cards and founder 1-click approval modal.',
    assigned_to: 'mem_ajay',
    priority: 'high',
    status: 'doing',
    required_skills: ['React / Next.js Development', 'Interactive Data Visualizations & Flowcharts'],
    estimated_hours: 10,
    deadline: '2026-08-24',
    created_at: '2026-08-17T11:00:00Z',
  },
  {
    id: 'tsk_05',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_03',
    project_name: 'FinFlow High-Frequency Engine',
    title: 'PostgreSQL Row-Level-Security performance index audit',
    description: 'Ensure cross-tenant query latency is under 15ms during high load.',
    assigned_to: 'mem_sara',
    priority: 'high',
    status: 'todo',
    required_skills: ['PostgreSQL & Supabase Multi-Tenancy', 'DevOps & Docker Deployment'],
    estimated_hours: 12,
    deadline: '2026-08-25',
    created_at: '2026-08-18T13:00:00Z',
  },
  {
    id: 'tsk_06',
    workspace_id: 'ws_leadlinked_01',
    project_id: 'prj_01',
    project_name: 'LeadLinked B2B Outbound Engine',
    title: 'Draft master client SLA terms & deliverability guarantees',
    description: 'Prepare enterprise service level agreements with 99.9% uptime commitments.',
    assigned_to: 'mem_elena',
    priority: 'medium',
    status: 'todo',
    required_skills: ['Client SLA & Legal Agreements', 'Stripe Billing & Cashflow Management'],
    estimated_hours: 5,
    deadline: '2026-08-27',
    created_at: '2026-08-19T09:30:00Z',
  },
];

export const LEADLINKED_INVOICES: Invoice[] = [
  {
    id: 'inv_101',
    workspace_id: 'ws_leadlinked_01',
    invoice_number: 'INV-2026-101',
    client_name: 'Apex Dynamics Corp',
    client_email: 'billing@apexdynamics.com',
    amount: 14250,
    currency: 'USD',
    status: 'paid',
    issue_date: '2026-08-01',
    due_date: '2026-08-15',
    project_name: 'Apex Robotics SaaS Redesign',
  },
  {
    id: 'inv_102',
    workspace_id: 'ws_leadlinked_01',
    invoice_number: 'INV-2026-102',
    client_name: 'FinFlow Global',
    client_email: 'accounts@finflow.io',
    amount: 22500,
    currency: 'USD',
    status: 'sent',
    issue_date: '2026-08-10',
    due_date: '2026-08-24',
    project_name: 'FinFlow High-Frequency Engine',
  },
  {
    id: 'inv_103',
    workspace_id: 'ws_leadlinked_01',
    invoice_number: 'INV-2026-098',
    client_name: 'Kroma Studio',
    client_email: 'finance@kromastudio.design',
    amount: 8000,
    currency: 'USD',
    status: 'overdue',
    issue_date: '2026-07-28',
    due_date: '2026-08-11',
    project_name: 'Kroma Brand Identity & Asset System',
  },
  {
    id: 'inv_104',
    workspace_id: 'ws_leadlinked_01',
    invoice_number: 'INV-2026-103',
    client_name: 'LeadLinked Pilot Client',
    client_email: 'founder@pilotclient.com',
    amount: 17500,
    currency: 'USD',
    status: 'draft',
    issue_date: '2026-08-19',
    due_date: '2026-09-02',
    project_name: 'LeadLinked B2B Outbound Engine',
  },
];

export const LEADLINKED_EXPENSES: Expense[] = [
  {
    id: 'exp_01',
    workspace_id: 'ws_leadlinked_01',
    name: 'Supabase Cloud Enterprise Database Tier',
    category: 'software',
    amount: 250,
    currency: 'USD',
    date: '2026-08-01',
    project_id: 'prj_01',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'exp_02',
    workspace_id: 'ws_leadlinked_01',
    name: 'OpenAI / DeepSeek LLM Inference API Token Pool',
    category: 'software',
    amount: 480,
    currency: 'USD',
    date: '2026-08-10',
    project_id: 'prj_01',
    created_at: '2026-08-10T12:00:00Z',
  },
  {
    id: 'exp_03',
    workspace_id: 'ws_leadlinked_01',
    name: 'Apollo Lead Enrichment API Monthly Plan',
    category: 'marketing',
    amount: 320,
    currency: 'USD',
    date: '2026-08-12',
    project_id: 'prj_01',
    created_at: '2026-08-12T09:00:00Z',
  },
];

export const LEADLINKED_DOCUMENTS: Document[] = [
  {
    id: 'doc_01',
    workspace_id: 'ws_leadlinked_01',
    title: 'LeadLinked Outbound Lead Qualification Playbook',
    type: 'sop',
    category: 'Sales & Ops',
    tags: ['Outbound', 'Lead Gen', 'SOP', 'Standard'],
    created_by_name: 'Mohammed Shezan Ahmed',
    updated_at: '2026-08-15T14:30:00Z',
    content: `<h1>LeadLinked Outbound Standard Operating Procedure</h1>
<p>This document specifies the exact protocol for identifying, enriching, and qualifying enterprise leads.</p>
<h2>Step 1: Automated Ideal Customer Profile (ICP) Matching</h2>
<p>Filter targets by company headcount (10-250), verified ARR, and active hiring in engineering/sales.</p>
<h2>Step 2: Hyper-Personalized AI Hook Generation</h2>
<p>Extract recent founder podcasts, hiring posts, and product updates to craft personalized 3-sentence hooks.</p>
<h2>Step 3: Founder Review & Meeting Booking</h2>
<p>Review high-affinity leads in the Qontro command center and dispatch with 1-click human approval.</p>`,
  },
  {
    id: 'doc_02',
    workspace_id: 'ws_leadlinked_01',
    title: 'LeadLinked Master Client Agreement & SLA 2026',
    type: 'contract',
    category: 'Legal',
    tags: ['Contracts', 'Legal', 'Master Agreement'],
    created_by_name: 'Elena Rostova',
    updated_at: '2026-08-16T10:00:00Z',
    content: `<h1>Master Service Agreement & Performance SLA</h1>
<p>Between <strong>LeadLinked</strong> ("Company") and the Client.</p>
<h3>1. Qualified Meeting SLA</h3>
<p>All delivered prospective leads must meet strict qualification criteria including budget authorization and active need.</p>
<h3>2. Data Privacy & Compliance</h3>
<p>100% GDPR and CAN-SPAM compliant enrichment with zero non-compliant outreach channels.</p>`,
  },
  {
    id: 'doc_03',
    workspace_id: 'ws_leadlinked_01',
    title: 'High-Ticket B2B Outreach Pitch Deck & Offer Blueprint',
    type: 'template',
    category: 'Sales',
    tags: ['Sales', 'Pitch', 'Proposal'],
    created_by_name: 'Mohammed Shezan Ahmed',
    updated_at: '2026-08-18T16:20:00Z',
    content: `<h1>LeadLinked: The Founder Sales Machine</h1>
<p>Prepared for Founder & Executive Teams.</p>
<h3>Core Value Proposition</h3>
<p>We replace random manual outbound with an AI-orchestrated lead generation engine delivering 15-25 qualified sales conversations monthly.</p>`,
  },
];

export const LEADLINKED_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec_01',
    workspace_id: 'ws_leadlinked_01',
    type: 'assignment',
    title: 'Reassign Copywriting Task from Ahmed to Ajay',
    description: 'Ahmed is currently overloaded at 95% capacity and writing is outside his core 9.8/10 UI/UX strength. Ajay has a 9.5/10 Copywriting rating and 45% available bandwidth.',
    target_task_id: 'tsk_02',
    recommended_member_id: 'mem_ajay',
    current_member_id: 'mem_ahmed',
    match_score: 94,
    reasons: [
      'Ajay has 9.5/10 Copywriting skill rating with 38 verified tasks.',
      'Ahmed is overloaded at 95% capacity across multiple design deliverables.',
      'Kroma deadline is in 48 hours; reassigning eliminates a projected delivery delay.',
    ],
    status: 'pending',
    created_at: '2026-08-19T06:00:00Z',
  },
  {
    id: 'rec_02',
    workspace_id: 'ws_leadlinked_01',
    type: 'overload',
    title: 'Burnout Warning: Ahmed Tariq Capacity Alert',
    description: 'Ahmed has 3 urgent design tasks due within 72 hours across 2 different clients.',
    recommended_member_id: 'mem_ahmed',
    match_score: 89,
    reasons: [
      'Ahmed is at 95% workload threshold.',
      'Simultaneously active on Apex Robotics and Kroma Brand System.',
      'Recommendation: Rebalance non-critical tasks to prevent quality degradation.',
    ],
    status: 'pending',
    created_at: '2026-08-19T06:30:00Z',
  },
  {
    id: 'rec_03',
    workspace_id: 'ws_leadlinked_01',
    type: 'deadline_risk',
    title: 'At-Risk Project: Kroma Brand System Health (42%)',
    description: 'Project is 3 days from deadline with incomplete copy tasks and 1 overdue invoice ($8,000).',
    reasons: [
      'Task completion pace is 35% below expected velocity.',
      'Invoice INV-2026-098 is 9 days overdue; recommend payment check before releasing master repo.',
    ],
    status: 'pending',
    created_at: '2026-08-19T07:15:00Z',
  },
];

export const LEADLINKED_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act_01',
    workspace_id: 'ws_leadlinked_01',
    type: 'ai',
    action: 'AI Operations Manager identified workload imbalance and generated assignment recommendation',
    actor_name: 'AI Agent',
    created_at: '2026-08-20T05:30:00Z',
  },
  {
    id: 'act_02',
    workspace_id: 'ws_leadlinked_01',
    type: 'task',
    action: 'Completed task: Audit and finalise dark minimalist component tokens',
    actor_name: 'Ahmed Tariq',
    created_at: '2026-08-18T17:00:00Z',
  },
  {
    id: 'act_03',
    workspace_id: 'ws_leadlinked_01',
    type: 'invoice',
    action: 'Received payment for invoice INV-2026-101 ($14,250)',
    actor_name: 'Finance Lead',
    created_at: '2026-08-15T11:00:00Z',
  },
];

export const LEADLINKED_TASK_HISTORIES: TaskHistory[] = [
  {
    id: 'th_01',
    task_id: 'tsk_03',
    workspace_id: 'ws_leadlinked_01',
    action: 'Status changed',
    actor_name: 'Ahmed Tariq',
    previous_value: 'doing',
    new_value: 'completed',
    created_at: '2026-08-18T17:00:00Z',
  },
  {
    id: 'th_02',
    task_id: 'tsk_02',
    workspace_id: 'ws_leadlinked_01',
    action: 'Status changed',
    actor_name: 'Mohammed Shezan Ahmed',
    previous_value: 'todo',
    new_value: 'blocked',
    created_at: '2026-08-19T08:00:00Z',
  },
];
