import { Workspace, WorkspaceMember, Project, Task, Skill, Invoice, Document, AIRecommendation } from '@/types';

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws_hyperion_01',
  name: 'Hyperion Labs',
  slug: 'hyperion-labs',
  owner_id: 'usr_founder_01',
  currency: 'USD',
  created_at: new Date().toISOString(),
};

export const INITIAL_MEMBERS: WorkspaceMember[] = [
  {
    id: 'mem_shezan',
    workspace_id: 'ws_hyperion_01',
    user_id: 'usr_founder_01',
    name: 'Shezan (Founder)',
    email: 'shezan@hyperion.io',
    role: 'owner',
    designation: 'Product Lead & Founder',
    workload_percentage: 65,
    status: 'active',
    joined_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'mem_ajay',
    workspace_id: 'ws_hyperion_01',
    user_id: 'usr_ajay_02',
    name: 'Ajay Verma',
    email: 'ajay@hyperion.io',
    role: 'member',
    designation: 'Senior Frontend & Copy Lead',
    workload_percentage: 45,
    status: 'active',
    joined_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 'mem_sara',
    workspace_id: 'ws_hyperion_01',
    user_id: 'usr_sara_03',
    name: 'Sara Lin',
    email: 'sara@hyperion.io',
    role: 'admin',
    designation: 'Fullstack & Cloud Architect',
    workload_percentage: 88,
    status: 'busy',
    joined_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'mem_ahmed',
    workspace_id: 'ws_hyperion_01',
    user_id: 'usr_ahmed_04',
    name: 'Ahmed Tariq',
    email: 'ahmed@hyperion.io',
    role: 'member',
    designation: 'UI/UX & Design Systems',
    workload_percentage: 95,
    status: 'busy',
    joined_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'mem_elena',
    workspace_id: 'ws_hyperion_01',
    user_id: 'usr_elena_05',
    name: 'Elena Rostova',
    email: 'elena@hyperion.io',
    role: 'member',
    designation: 'Growth & Client Ops',
    workload_percentage: 30,
    status: 'active',
    joined_at: '2026-04-10T08:00:00Z',
  },
];

export const INITIAL_SKILLS: Skill[] = [
  { id: 'sk_1', user_id: 'usr_ajay_02', workspace_id: 'ws_hyperion_01', skill_name: 'Copywriting & Content Strategy', score: 9.4, category: 'content', verified_tasks_count: 34 },
  { id: 'sk_2', user_id: 'usr_ajay_02', workspace_id: 'ws_hyperion_01', skill_name: 'React / Next.js Development', score: 8.8, category: 'engineering', verified_tasks_count: 22 },
  { id: 'sk_3', user_id: 'usr_ajay_02', workspace_id: 'ws_hyperion_01', skill_name: 'Technical Documentation', score: 9.0, category: 'content', verified_tasks_count: 19 },
  
  { id: 'sk_4', user_id: 'usr_sara_03', workspace_id: 'ws_hyperion_01', skill_name: 'PostgreSQL & Supabase Architecture', score: 9.6, category: 'engineering', verified_tasks_count: 48 },
  { id: 'sk_5', user_id: 'usr_sara_03', workspace_id: 'ws_hyperion_01', skill_name: 'System Security & Auth', score: 9.1, category: 'engineering', verified_tasks_count: 28 },
  { id: 'sk_6', user_id: 'usr_sara_03', workspace_id: 'ws_hyperion_01', skill_name: 'DevOps & CI/CD', score: 8.5, category: 'engineering', verified_tasks_count: 15 },
  
  { id: 'sk_7', user_id: 'usr_ahmed_04', workspace_id: 'ws_hyperion_01', skill_name: 'Figma & Design Systems', score: 9.7, category: 'design', verified_tasks_count: 52 },
  { id: 'sk_8', user_id: 'usr_ahmed_04', workspace_id: 'ws_hyperion_01', skill_name: 'Micro-Animations & Motion UI', score: 8.9, category: 'design', verified_tasks_count: 31 },
  { id: 'sk_9', user_id: 'usr_ahmed_04', workspace_id: 'ws_hyperion_01', skill_name: 'Landing Page Conversion UX', score: 9.2, category: 'marketing', verified_tasks_count: 26 },

  { id: 'sk_10', user_id: 'usr_elena_05', workspace_id: 'ws_hyperion_01', skill_name: 'Client Communication & Contracts', score: 9.5, category: 'operations', verified_tasks_count: 41 },
  { id: 'sk_11', user_id: 'usr_elena_05', workspace_id: 'ws_hyperion_01', skill_name: 'Financial Billing & Invoicing', score: 8.9, category: 'operations', verified_tasks_count: 30 },
  { id: 'sk_12', user_id: 'usr_elena_05', workspace_id: 'ws_hyperion_01', skill_name: 'Paid Ad Campaign Optimization', score: 8.4, category: 'marketing', verified_tasks_count: 18 },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_01',
    workspace_id: 'ws_hyperion_01',
    name: 'Apex Robotics SaaS Redesign',
    client_name: 'Apex Dynamics Corp',
    description: 'Complete brand repositioning, dark dashboard UI system, and customer portal architecture.',
    budget: 28500,
    deadline: '2026-08-28',
    status: 'active',
    health_score: 92,
    total_tasks: 14,
    completed_tasks: 9,
    lead_member_id: 'mem_ahmed',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prj_02',
    workspace_id: 'ws_hyperion_01',
    name: 'FinFlow High-Frequency Engine',
    client_name: 'FinFlow Global',
    description: 'Supabase PostgreSQL multi-tenant backend migration and real-time ledger sync.',
    budget: 45000,
    deadline: '2026-08-23',
    status: 'warning',
    health_score: 64,
    total_tasks: 18,
    completed_tasks: 7,
    lead_member_id: 'mem_sara',
    created_at: '2026-08-05T12:00:00Z',
  },
  {
    id: 'prj_03',
    workspace_id: 'ws_hyperion_01',
    name: 'Kroma Brand Identity & Asset Engine',
    client_name: 'Kroma Studio',
    description: 'Design guidelines, token library, component catalog, and sales landing page.',
    budget: 16000,
    deadline: '2026-08-21',
    status: 'critical',
    health_score: 41,
    total_tasks: 12,
    completed_tasks: 4,
    lead_member_id: 'mem_ahmed',
    created_at: '2026-08-08T09:00:00Z',
  },
  {
    id: 'prj_04',
    workspace_id: 'ws_hyperion_01',
    name: 'OmniHealth Patient Portal',
    client_name: 'OmniHealth Inc',
    description: 'HIPAA compliant dashboard and patient intake onboarding flow.',
    budget: 38000,
    deadline: '2026-09-15',
    status: 'planning',
    health_score: 100,
    total_tasks: 8,
    completed_tasks: 0,
    lead_member_id: 'mem_ajay',
    created_at: '2026-08-15T15:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk_01',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_01',
    project_name: 'Apex Robotics SaaS Redesign',
    title: 'Audit and finalise dark glassmorphism component tokens',
    description: 'Extract standard border radiuses, surface opacities, and font pairings for Apex portal.',
    assigned_to: 'mem_ahmed',
    priority: 'high',
    status: 'completed',
    required_skills: ['Figma & Design Systems', 'Micro-Animations & Motion UI'],
    estimated_hours: 6,
    deadline: '2026-08-18',
    created_at: '2026-08-12T10:00:00Z',
    completed_at: '2026-08-18T16:00:00Z',
  },
  {
    id: 'tsk_02',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_02',
    project_name: 'FinFlow High-Frequency Engine',
    title: 'PostgreSQL Row-Level-Security performance audit & indexing',
    description: 'Ensure cross-tenant query latency is under 15ms under 10k transactions load test.',
    assigned_to: 'mem_sara',
    priority: 'urgent',
    status: 'doing',
    required_skills: ['PostgreSQL & Supabase Architecture', 'System Security & Auth'],
    estimated_hours: 14,
    deadline: '2026-08-22',
    created_at: '2026-08-14T11:00:00Z',
  },
  {
    id: 'tsk_03',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_03',
    project_name: 'Kroma Brand Identity & Asset Engine',
    title: 'High-converting sales page copywriting & hook hierarchy',
    description: 'Write 5 core benefit blocks, founder story, and clear CTA structure for agency offering.',
    assigned_to: 'mem_ahmed', // Intentionally mismatched to trigger AI recommendation to Ajay
    priority: 'urgent',
    status: 'blocked',
    required_skills: ['Copywriting & Content Strategy', 'Landing Page Conversion UX'],
    estimated_hours: 8,
    deadline: '2026-08-20',
    created_at: '2026-08-16T09:00:00Z',
  },
  {
    id: 'tsk_04',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_01',
    project_name: 'Apex Robotics SaaS Redesign',
    title: 'Build interactive sensor telemetry graph widgets',
    description: 'Use Canvas / SVG charts with real-time smooth animation and zero frame drops.',
    assigned_to: 'mem_ajay',
    priority: 'high',
    status: 'doing',
    required_skills: ['React / Next.js Development', 'Micro-Animations & Motion UI'],
    estimated_hours: 10,
    deadline: '2026-08-24',
    created_at: '2026-08-15T14:00:00Z',
  },
  {
    id: 'tsk_05',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_02',
    project_name: 'FinFlow High-Frequency Engine',
    title: 'Automated Stripe Webhook reconciliation service',
    description: 'Handle duplicate events, retry buffers, and invoice dispatch callbacks.',
    assigned_to: 'mem_sara',
    priority: 'high',
    status: 'todo',
    required_skills: ['System Security & Auth', 'DevOps & CI/CD'],
    estimated_hours: 12,
    deadline: '2026-08-23',
    created_at: '2026-08-16T12:00:00Z',
  },
  {
    id: 'tsk_06',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_04',
    project_name: 'OmniHealth Patient Portal',
    title: 'Draft master client service agreement & SLA terms',
    description: 'Prepare final pricing annexure and HIPAA compliance liability guarantees.',
    assigned_to: 'mem_elena',
    priority: 'medium',
    status: 'todo',
    required_skills: ['Client Communication & Contracts', 'Financial Billing & Invoicing'],
    estimated_hours: 5,
    deadline: '2026-08-27',
    created_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 'tsk_07',
    workspace_id: 'ws_hyperion_01',
    project_id: 'prj_03',
    project_name: 'Kroma Brand Identity & Asset Engine',
    title: 'Export SVG icon suite and responsive web typography tokens',
    description: 'Generate webfont subsets and standalone vector icons for production bundle.',
    assigned_to: 'mem_ahmed',
    priority: 'medium',
    status: 'todo',
    required_skills: ['Figma & Design Systems'],
    estimated_hours: 6,
    deadline: '2026-08-21',
    created_at: '2026-08-17T15:00:00Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_101',
    workspace_id: 'ws_hyperion_01',
    invoice_number: 'INV-2026-089',
    client_name: 'Apex Dynamics Corp',
    client_email: 'billing@apexdynamics.com',
    amount: 14250,
    currency: 'USD',
    status: 'paid',
    issue_date: '2026-08-01',
    due_date: '2026-08-15',
    project_name: 'Apex Robotics SaaS Redesign',
  },
  {
    id: 'inv_102',
    workspace_id: 'ws_hyperion_01',
    invoice_number: 'INV-2026-090',
    client_name: 'FinFlow Global',
    client_email: 'accounts@finflow.io',
    amount: 22500,
    currency: 'USD',
    status: 'sent',
    issue_date: '2026-08-10',
    due_date: '2026-08-24',
    project_name: 'FinFlow High-Frequency Engine',
  },
  {
    id: 'inv_103',
    workspace_id: 'ws_hyperion_01',
    invoice_number: 'INV-2026-084',
    client_name: 'Kroma Studio',
    client_email: 'finance@kromastudio.design',
    amount: 8000,
    currency: 'USD',
    status: 'overdue',
    issue_date: '2026-07-28',
    due_date: '2026-08-11',
    project_name: 'Kroma Brand Identity & Asset Engine',
  },
  {
    id: 'inv_104',
    workspace_id: 'ws_hyperion_01',
    invoice_number: 'INV-2026-091',
    client_name: 'OmniHealth Inc',
    client_email: 'procure@omnihealth.org',
    amount: 19000,
    currency: 'USD',
    status: 'draft',
    issue_date: '2026-08-19',
    due_date: '2026-09-02',
    project_name: 'OmniHealth Patient Portal',
  },
];

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'doc_01',
    workspace_id: 'ws_hyperion_01',
    title: 'Standard Client Onboarding & Tech Handoff SOP',
    type: 'sop',
    category: 'Operations',
    tags: ['Onboarding', 'SOP', 'Standard'],
    created_by_name: 'Shezan (Founder)',
    updated_at: '2026-08-10T14:30:00Z',
    content: `<h1>Client Onboarding Standard Operating Procedure</h1>
<p>This document defines the exact 5-step onboarding protocol for every new enterprise agency client.</p>
<h2>Step 1: Automated Slack & Workspace Provisioning</h2>
<p>Send automated invitation within 2 hours of signed contract and 50% retainer deposit confirmation.</p>
<h2>Step 2: Technical Discovery & Architecture Blueprint</h2>
<p>Conduct a 45-minute synchronous scoping call. Document all database schemas, API keys, and target SLA requirements.</p>
<h2>Step 3: Milestone & Sprint Roadmap Lock</h2>
<p>Define weekly delivery cycles in Qontro with explicit skill assignments and transparent review gates.</p>`,
  },
  {
    id: 'doc_02',
    workspace_id: 'ws_hyperion_01',
    title: 'Fixed-Bid Software Service Agreement Template 2026',
    type: 'contract',
    category: 'Legal',
    tags: ['Contracts', 'Legal', 'Master Agreement'],
    created_by_name: 'Elena Rostova',
    updated_at: '2026-08-14T09:00:00Z',
    content: `<h1>Master Software Service Agreement</h1>
<p>Between <strong>Hyperion Labs</strong> ("Service Provider") and the Client specified in Project Schedule.</p>
<h3>1. Intellectual Property Transfer</h3>
<p>All custom code, designs, and architectural deliverables become 100% Client property upon complete settlement of final invoice.</p>
<h3>2. Warranty & Bug Fix Window</h3>
<p>Standard 30-day post-launch warranty included with zero charge for scope-defined regressions.</p>`,
  },
  {
    id: 'doc_03',
    workspace_id: 'ws_hyperion_01',
    title: 'High-Converting B2B SaaS Proposal Blueprint',
    type: 'template',
    category: 'Sales',
    tags: ['Sales', 'Pitch', 'Proposal'],
    created_by_name: 'Shezan (Founder)',
    updated_at: '2026-08-17T16:20:00Z',
    content: `<h1>B2B Proposal: Engineering & Product Scale</h1>
<p>Prepared for Executive Leadership.</p>
<h3>Executive Summary</h3>
<p>How we help you replace fragmented agency chaos with a dedicated senior squad delivering production code in 14-day sprints.</p>`,
  },
];

export const INITIAL_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec_01',
    workspace_id: 'ws_hyperion_01',
    type: 'assignment',
    title: 'Reassign Copywriting Task from Ahmed to Ajay',
    description: 'Ahmed is currently overloaded at 95% capacity and writing is outside his core 9.7/10 UI/UX strength. Ajay has a 9.4/10 Copywriting rating and 45% available bandwidth.',
    target_task_id: 'tsk_03',
    recommended_member_id: 'mem_ajay',
    current_member_id: 'mem_ahmed',
    match_score: 94,
    reasons: [
      'Ajay has 9.4/10 Copywriting skill score with 34 verified tasks.',
      'Ahmed is currently overloaded at 95% capacity with 3 active projects.',
      'Kroma deadline is in 48 hours; reassigning prevents a guaranteed delivery delay.',
    ],
    status: 'pending',
    created_at: '2026-08-19T06:00:00Z',
  },
  {
    id: 'rec_02',
    workspace_id: 'ws_hyperion_01',
    type: 'overload',
    title: 'Burnout Warning: Ahmed Tariq Capacity Alert',
    description: 'Ahmed has 3 active urgent project tasks due within 72 hours across 2 different clients.',
    recommended_member_id: 'mem_ahmed',
    match_score: 88,
    reasons: [
      'Ahmed is at 95% workload threshold.',
      'Active on Apex Robotics and Kroma Studio simultaneously.',
      'Suggestion: Delegate icon export task to external library or push deadline by 2 days.',
    ],
    status: 'pending',
    created_at: '2026-08-19T06:30:00Z',
  },
  {
    id: 'rec_03',
    workspace_id: 'ws_hyperion_01',
    type: 'deadline_risk',
    title: 'At-Risk Project: Kroma Brand Engine Health (41%)',
    description: 'Project is 4 days away from deadline with 8 out of 12 tasks incomplete and 1 overdue invoice ($8,000).',
    reasons: [
      'Completion velocity is currently 33% below target.',
      'Invoice INV-2026-084 is 8 days overdue; review milestone payment before releasing source repo.',
    ],
    status: 'pending',
    created_at: '2026-08-19T07:15:00Z',
  },
];
